apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-server
  labels:
    app: admission-server
spec:
  selector:
    matchLabels:
      app: admission-server
  template:
    metadata:
      labels:
        app: admission-server
    spec:
      serviceAccountName: admission-controller
      containers:
      - name: server
        image: {{ .Values.werf.image.admission }}
        command:
        - /app/serverd
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Values.server.resources.requests.mem }}
            cpu: {{ .Values.server.resources.requests.cpu }}
          limits:
            memory: {{ .Values.server.resources.limits.mem }}
        ports:
        - containerPort: 8443
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/certs
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: admission-tls
---
apiVersion: v1
kind: Service
metadata:
  name: admission-server
spec:
  selector:
    app: admission-server
  ports:
    - port: 443
      targetPort: 8443
