apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: probes-validation
webhooks:
  - name: probes-validation.default.svc
    clientConfig:
      service:
        name: admission-server
        namespace: admission-controller
        path: "/validate"
      caBundle:  {{ .Values.tls.ca | b64enc }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments", "statefulsets"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1"]
