apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: default
spec:
  limits:
  - max:
      cpu: "0m"
      memory: 0Gi
    min:
      cpu: 0m
      memory: 0Mi
    default:
      cpu: "1m"
    type: Pod
  - default:
      cpu: 0m
      memory: 0Mi
    defaultRequest:
      cpu: 500m
      memory: 500Mi
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 100m
      memory: 100Mi
    type: Container
