apiVersion: v2
name: k8s-infra
version: 1.0.0
dependencies:
- name: apf
  version: ~1
  repository: ""
  condition: apf.enabled
  export-values:
  - parent: werf
    child: werf
- name: admission-controller
  version: ~1
  repository: ""
  condition: admission-controller.enabled
  export-values:
  - parent: werf
    child: werf
- name: resource-quota
  version: ~1
  repository: ""
  condition: resource-quota.enabled
  export-values:
  - parent: werf
    child: werf
- name: limit-range
  version: ~1
  repository: ""
  condition: limit-range.enabled
  export-values:
  - parent: werf
    child: werf
