apiVersion: v2
name: k8s-infra
version: 1.0.0
dependencies:
- name: apf
  version: ~1
  repository: ""
  condition: apf.enabled
  export-values:
  - parent: werf
    child: werf
- name: rook-ceph
  version: ~1
  repository: "https://charts.rook.io/release"
  condition: rook-ceph-operator.enabled
  export-values:
  - parent: werf
    child: werf
- name: rook-ceph-cluster
  version: ~1
  repository: "https://charts.rook.io/release"
  condition: rook-ceph-cluster.enabled
  export-values:
  - parent: werf
    child: werf

