{{ range $namespace, $value := .Values.apf }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $namespace }}-crawler
  namespace: {{ $namespace }}
  labels:
    kubernetes.io/name: {{ $namespace }}-crawler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $namespace }}-crawler
  namespace: {{ $namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "deployments", "statefulsets"]
    verbs: ["list", "get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $namespace }}-crawler-binding
  namespace: {{ $namespace }}
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ $namespace }}-crawler
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $namespace }}-crawler
{{ end }}
